### ISSUE TITLE
Requirement : pip install passbolt    ERROR: Could not find a version that satisfies the requirement passbolt 

### ISSUE THREAD

**Issue by khalangy** [daniel-lynch/daniel_lynch.passbolt#7]
Hello,
When I try to install passbolt module from pip I get this error : 
```
pip install passbolt   
ERROR: Could not find a version that satisfies the requirement passbolt (from versions: none)
ERROR: No matching distribution found for passbolt
```
I installed others python libraries (py-passbolt, passbolt-python-api, passbolt-api) but I still had the error.

Could you help me with this problem please ? 

Thanks

**Comment by daniel-lynch** [comment]
Hey @khalangy sorry about that. I removed the library from PyPI because of a trademark issue and I'm in the midst of updating documentation. Try one of the methods below to install the python library and you should be good to go!

```
pip install git+https://github.com/daniel-lynch/py-passbolt
``` 

or

```
git clone https://github.com/daniel-lynch/py-passbolt.git
cd passbolt
python3 setup.py install
```

Kind regards

**Comment by khalangy** [comment]
Thanks a lot, it works :) 
Have a nice day 
Best regards
